server:
  port: 9910
spring:
  profiles: default
  application:
    name: oauth2-service
logging:
  level:
    org.springframework.security: debug
    com.alibaba: debug
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9900/oauth/token
      user-authorization-uri: http://localhost:9900/oauth/authorize
      client-id: app
      client-secret: app123
    resource:
      user-info-uri: http://localhost:9900/me
#      jwt:
#        key-uri: http://localhost:9900/oauth/token_key